version: '3.9'

services:
  mapdragon:
    build:
      context: ./map-dragon
      dockerfile: Dockerfile
      args:
        ENV: loc
    networks:
      - shared_network
    container_name: mapdragon_app
    ports:
      - "5173:5173"

  locutus:
    build:
      context: ./locutus
      dockerfile: Dockerfile
    container_name: locutus_api
    networks:
      - shared_network
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=local
      - FLASK_RUN_PORT=80
      - DB_TYPE=${DB_TYPE}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    #  - MONGO_URI=${MONGO_URI}
      - MONGO_URI=${FIRESTORE_MONGO_URI}
      - UMLS_API_KEY=${UMLS_API_KEY}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/mapdragon-unified-creds.json
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - shared_network
    # Ensures MongoDB is fully initialized before other services start
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - mapdragon
      - locutus
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge

volumes:
  mongo-data: