version: '3.9'

services:
  mapdragon:
    build:
      context: ./map-dragon
      dockerfile: Dockerfile
      args:
        ENV: loc
    networks:
      - shared_network
    container_name: mapdragon_app
    ports:
      - "5173:5173"
    depends_on:
      - locutus
      - mongo  # Add dependency on MongoDB

  locutus:
    build:
      context: ./locutus
      dockerfile: Dockerfile.mac
    container_name: locutus_api
    networks:
      - shared_network
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=local
      - FLASK_RUN_PORT=80
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - MONGO_URI=mongodb://${DB_NAME}:${DB_PASSWORD}@mongo:27017  # Add MongoDB connection string
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/mapdragon-unified-creds.json
    depends_on:
      - mongo  # Add dependency on MongoDB

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - mapdragon
      - locutus
    ports:
      - "8080:80" # Expose the proxy on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge

volumes:
  mongo-data: