version: '3.9'

services:
  mapdragon:
    build:
      context: ./map-dragon
      dockerfile: Dockerfile
      args:
        ENV: loc
    networks:
      - mapdragon-network
    container_name: mapdragon_app
    ports:
      - "5173:5173"

  locutus:
    build:
      context: ./locutus
      dockerfile: Dockerfile
    container_name: locutus_api
    networks:
      - mapdragon-network
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=local
      - FLASK_RUN_PORT=80
      - DB_TYPE=${DB_TYPE}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - MONGO_URI=${MONGO_URI}
      # - MONGO_URI=${FIRESTORE_MONGO_URI}
      - UMLS_API_KEY=${UMLS_API_KEY}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/mapdragon-unified-creds.json
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - mapdragon
      - locutus
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mapdragon-network

networks:
  mapdragon-network:
    external: true

volumes:
  mongo-data:
