# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when manually triggered.

name: 'Manual Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., dev, uat, prod, alpha, kf)'
        required: true
        type: string
        default: 'dev'
      version:
        description: 'Optional version for the deployment'
        required: true
        type: string
        default: 'v0.0.0-env'
      deploy_branch:
        description: 'Branch to deploy to the environment'
        required: true
        type: string
        default: 'main'

env:
  VITE_CLIENT_ID: ${{ vars.VITE_CLIENT_ID }}
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: ${{ vars.GCP_REGION }}
  SERVICE: ${{ vars.GCP_SERVICE }}
  GCP_CREDENTIALS:  ${{ secrets.GCP_CREDENTIALS }}
  UMLS_API_KEY: ${{ secrets.UMLS_API_KEY }}
  DOCKER_TAG: "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_SERVICE }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}"

jobs:
  
  deploy:
    runs-on: 'ubuntu-latest'

    environment:
      name: ${{ github.event.inputs.environment }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.event.inputs.deploy_branch }} # This branch is deployed
      
      - name: "Deploying ${{ github.event.inputs.deploy_branch }} to ${{ github.event.inputs.environment }}"
        run: echo "Deploying ${{ github.event.inputs.deploy_branch }} to ${{ github.event.inputs.environment }}"
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Configure Git user'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: 'Set Version'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted Version: ${VERSION}"

      - name: 'Build Docker Image'
        run: |-
          echo "DOCKER_TAG=${{ env.DOCKER_TAG }}" >> $GITHUB_ENV 

          # docker build -t "${env.DOCKER_TAG}" --build-arg ENV=${{ github.event.inputs.environment }} .
          docker build -t "${{ env.DOCKER_TAG }}" --build-arg VITE_CLIENT_ID=${{ env.VITE_CLIENT_ID }} --build-arg VITE_MAPDRAGON_VERSION=${{ github.event.inputs.version }} .

      - name: 'Push Docker Image'
        run: |-
          docker push "${{ env.DOCKER_TAG }}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE }}
          region: '${{ env.REGION }}'
          image: ${{ env.DOCKER_TAG }}
          env_vars: VERSION=${{ env.VERSION }}, UMLS_API_KEY=${{ env.UMLS_API_KEY }}
